[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lzxmodular"
authors = [{name = "Lars Larsen", email = "lars@lzxindustries.net"}]
dynamic = ["version", "description"]
